### ISSUE TITLE
ValueError: No weights to regularize.

### ISSUE THREAD

**Issue by loveJasmine** [guoyang9/NCF#1]
mldl@ub1604:~/ub16_prj/NCF/tensorflow$ python3 main.py --batch_size=128 --lr=0.00001 --embed_size=1
Loading training data finished!
Loading testing data finished!
2018-09-11 00:35:05.567812: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-11 00:35:05.660958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-11 00:35:05.661495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.49GiB
2018-09-11 00:35:05.661566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 113, in main
    train(train_data, test_data, user_size, item_size)
  File "main.py", line 47, in train
    model.build()
  File "/home/mldl/ub16_prj/NCF/tensorflow/NCF.py", line 196, in build
    self.create_model()
  File "/home/mldl/ub16_prj/NCF/tensorflow/NCF.py", line 169, in create_model
    self.regularizer, reg)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 190, in apply_regularization
    raise ValueError('No weights to regularize.')
ValueError: No weights to regularize.
mldl@ub1604:~/ub16_prj/NCF/tensorflow$

**Comment by guoyang9** [comment]
See the new implementation.
